log:
  level: 'debug'

grpc:
  port: 50051

metrics:
  cpu:
    enabled: true
    usagePercent: true
    userMode: true
    systemMode: true
    idle: true

  disk:
    enabled: true
    tps: true
    kbPerSec: true
    usage: true

  network:
    enabled: false
    topTalkersByProtocol: true
    topTalkersByTraffic: true