name: System-monitor tests

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.24

      - uses: actions/checkout@v4

      - name: Run golangci-lint
        run: |
          make lint
      

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.24
      - uses: actions/checkout@v4
      - run: go test -v -count=1 -race -timeout=1m ./...
