name: System-monitor tests

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.24

      - uses: actions/checkout@v4

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh  | \
            sh -s -- -b $HOME/bin v2.2.1

      - name: Run golangci-lint
        run: |
          $HOME/bin/golangci-lint run ./... -v
      

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ~1.24
      - uses: actions/checkout@v4
      - run: go test -v -count=1 -race -timeout=1m ./...
